//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rental
    {
        public int re_id { get; set; }
        public Nullable<System.DateTime> re_indate { get; set; }
        public Nullable<System.DateTime> re_outdate { get; set; }
        public string re_outsession { get; set; }
        public int re_tid { get; set; }
        public int re_rid { get; set; }
        public double re_deposit { get; set; }
        public double re_rentPrice { get; set; }
        public string re_paymentStatus { get; set; }
        public Nullable<System.DateTime> re_payDate { get; set; }
        public Nullable<double> re_outstanding { get; set; }
    
        public virtual tb_room tb_room { get; set; }
        public virtual tb_tenant tb_tenant { get; set; }
    }
}
