//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_attendance
    {
        [Display(Name = "Attendance ID")]
        public int atd_id { get; set; }
        [Display(Name = "Attendance Floor ID")]
        public int atd_fid { get; set; }
        [Display(Name = "Attendance Date")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> atd_check { get; set; }

        public virtual tb_floor tb_floor { get; set; }
    }
}
