//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_floor()
        {
            this.tb_attendance = new HashSet<tb_attendance>();
            this.tb_inventory = new HashSet<tb_inventory>();
            this.tb_room = new HashSet<tb_room>();
            this.tb_transaction = new HashSet<tb_transaction>();
        }
        [Display(Name = "Floor ID")]
        public int f_id { get; set; }
        [Display(Name = "Landlord ID")]
        public int f_lid { get; set; }



        [Display(Name = "Building")]

        public string f_building { get; set; }
        [Display(Name = "Wifi Password")]
        public string f_wifipwd { get; set; }
        [Display(Name = "Modem IP")]
        public string f_modemIP { get; set; }
        [Display(Name = "CCTV QR")]
        public string f_cctvqr { get; set; }
        [Display(Name = "Layout")]
        public string f_layout { get; set; }

        public int f_uid { get; set; }
        [Display(Name = "Floor")]
        public string f_desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_attendance> tb_attendance { get; set; }
        public virtual tb_landlord tb_landlord { get; set; }
        public virtual tb_user tb_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_inventory> tb_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_room> tb_room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_transaction> tb_transaction { get; set; }
    }
}
