//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_investors
    {
        public int i_id { get; set; }
        public int i_uid { get; set; }
        public int i_pid { get; set; }
        public int i_lot { get; set; }
        public double i_lotperc { get; set; }
    
        public virtual tb_profit tb_profit { get; set; }
        public virtual tb_user tb_user { get; set; }
    }
}
