//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_profit
    {
        public int p_id { get; set; }
        public System.DateTime p_date { get; set; }
        public double p_profit { get; set; }
        public int p_investorid { get; set; }
    
        public virtual tb_investors tb_investors { get; set; }
    }
}
