//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_rental
    {
        [Display(Name = "Profit ID")]
        public int re_id { get; set; }
        [Display(Name = "Check In")]
        public Nullable<System.DateTime> re_indate { get; set; }
        [Display(Name = "Check Out")]
        public Nullable<System.DateTime> re_outdate { get; set; }
        [Display(Name = "Check Out Session")]
        public string re_outsession { get; set; }
        [Display(Name = "Tenant ID")]
        public int re_tid { get; set; }
        [Display(Name = "Room ID")]
        public int re_rid { get; set; }
        [Display(Name = "Deposit")]
        public double re_deposit { get; set; }
        [Display(Name = "Price")]
        public double re_rentPrice { get; set; }
        [Display(Name = "Status")]
        public string re_paymentStatus { get; set; }
        [Display(Name = "Payment Date")]
        public Nullable<System.DateTime> re_payDate { get; set; }
        [Display(Name = "Outstanding")]
        public Nullable<double> re_outstanding { get; set; }
    
        public virtual tb_room tb_room { get; set; }
        public virtual tb_tenant tb_tenant { get; set; }
    }
}
