//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_reminder
    {
        public int rmd_id { get; set; }
        public string rmd_desc { get; set; }
        public int rmd_uid { get; set; }
    
        public virtual tb_user tb_user { get; set; }
    }
}
