//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tenant()
        {
            this.tb_rental = new HashSet<tb_rental>();
        }
    
        public int t_id { get; set; }
        public string t_name { get; set; }
        public int t_ic { get; set; }
        public string t_uploadic { get; set; }
        public string t_contract { get; set; }
        public string t_phone { get; set; }
        public string t_emergcont { get; set; }
        public int t_siriNo { get; set; }
        public int t_paymentStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_rental> tb_rental { get; set; }
    }
}
