//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_tenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_tenant()
        {
            this.tb_rental = new HashSet<tb_rental>();
        }
        [Display(Name = "Tenant ID")]
        public int t_id { get; set; }
        [Display(Name = "Name")]
        public string t_name { get; set; }
        [Display(Name = "IC")]
        public string t_ic { get; set; }
        [Display(Name = "IC Picture")]
        public string t_uploadic { get; set; }
        [Display(Name = "Contract")]
        public string t_contract { get; set; }
        [Display(Name = "Phone")]
        public string t_phone { get; set; }
        [Display(Name = "Emergency Contact")]
        public string t_emergcont { get; set; }
        [Display(Name = "Siri No")]
        public string t_siriNo { get; set; }
        [Display(Name = "Access Card")]
        public string t_accessCardNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_rental> tb_rental { get; set; }
    }
}
