//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanguardPro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_user()
        {
            this.tb_floor = new HashSet<tb_floor>();
            this.tb_investors = new HashSet<tb_investors>();
            this.tb_reminder = new HashSet<tb_reminder>();
        }
<<<<<<< HEAD
        [Display(Name = "User ID")]
=======
        [Display(Name ="User ID")]
>>>>>>> 82139065515aaac3ee3994bf9047bf6fd1ae97d8
        public int u_id { get; set; }
        [Display(Name = "Username")]
        public string u_username { get; set; }
        [Display(Name = "Password")]
        public string u_pwd { get; set; }
        [Display(Name = "Email")]
        public string u_email { get; set; }
        [Display(Name = "User Type")]
        public int u_usertype { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_floor> tb_floor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_investors> tb_investors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reminder> tb_reminder { get; set; }
    }
}
